GET http://inventory:8082/api/inventory?skuCode=iphone_15&quantity=10

###
POST http://order:8081/api/order HTTP/1.1
content-type: application/json

{
    "skuCode": "iphone_15",
    "price": "11.22",
    "quantity": 2
}


